# Generated by Django 2.0.13 on 2019-10-31 14:38

import uuid

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("datahubhel", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="TA120Sensor",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("id_sensor", models.CharField(max_length=60, unique=True)),
                ("key", models.CharField(max_length=128)),
                (
                    "datastreams",
                    models.ManyToManyField(blank=True, to="datahubhel.Datastream"),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="datahubhel.Sensor",
                    ),
                ),
                (
                    "thing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="datahubhel.Thing",
                    ),
                ),
            ],
            options={"abstract": False},
        )
    ]
