# Generated by Django 2.0.13 on 2019-10-24 13:40

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models
from django_extensions.db.fields import (
    CreationDateTimeField,
    ModificationDateTimeField,
)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datahubhel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TA120Sensor',
            fields=[
                ('id', models.UUIDField(
                    default=uuid.uuid4,
                    editable=False,
                    primary_key=True,
                    serialize=False)),
                ('created', CreationDateTimeField(
                    auto_now_add=True, verbose_name='created')),
                ('modified', ModificationDateTimeField(
                    auto_now=True, verbose_name='modified')),
                ('identifier', models.CharField(max_length=60, unique=True)),
                ('key', models.CharField(max_length=128)),
                ('datastreams', models.ManyToManyField(
                    to='datahubhel.Datastream', blank=True)),
                ('sensor', models.ForeignKey(
                    to='datahubhel.Sensor',
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='+')),
                ('thing', models.ForeignKey(
                    to='datahubhel.Thing',
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='physical_sensors')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
